/**
 * One-command launcher for JaMusic V2:
 *   1. Boots the bundled NodeLink audio server (pure Node.js — no Java needed).
 *   2. Waits until its REST API answers.
 *   3. Starts the Discord bot in this same process.
 *
 * Local:   npm start                      -> NodeLink on 127.0.0.1:<port>, bot attached to it
 * Render:  npm start (PORT is injected)   -> NodeLink binds 0.0.0.0:$PORT so the platform
 *                                            health check passes; the bot connects via localhost
 *
 * NodeLink resolves its own configuration *after* loading config files, so the
 * NODELINK_SERVER_HOST/PORT/PASSWORD vars exported here always win — even when a
 * nodelink/config.ts exists and shadows the generated nodelink/config.js.
 *
 * Environment:
 *   NODELINK_PASSWORD   shared password        (default: youshallnotpass)
 *   NODELINK_PORT       bundled server port    (default: $PORT on Render, else LAVALINK_PORT, else 3000)
 *   NODELINK_HOST       bind host              (default: 0.0.0.0 on Render, else 127.0.0.1)
 *   Set NODELINK_HOST to a remote hostname to skip the bundled server and connect externally.
 */
require("dotenv").config();

const { spawn, spawnSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const NODELINK_DIR = path.join(ROOT, "nodelink");
const MARKER = "// GENERATED BY scripts/start.js";

const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "0.0.0.0", "::1"]);
const bindHost = process.env.NODELINK_HOST || (process.env.PORT ? "0.0.0.0" : "127.0.0.1");
const port = Number(process.env.NODELINK_PORT || process.env.PORT || process.env.LAVALINK_PORT) || 3000;
const externalHost =
  process.env.NODELINK_HOST && !LOCAL_HOSTS.has(process.env.NODELINK_HOST.toLowerCase());

let nodeLink = null;
let shuttingDown = false;

/**
 * Kills NodeLink *and its cluster workers*.
 * A plain child.kill() leaves NodeLink's worker processes alive on Windows, and those
 * orphans keep squatting the port, which makes the next start fail to bind.
 */
function killNodeLinkTree() {
  if (!nodeLink || nodeLink.exitCode !== null || !nodeLink.pid) return;
  try {
    if (process.platform === "win32") {
      spawnSync("taskkill", ["/pid", String(nodeLink.pid), "/T", "/F"], { stdio: "ignore" });
    } else {
      // The child was spawned detached, so its PID is also its process-group id.
      try {
        process.kill(-nodeLink.pid, "SIGKILL");
      } catch {
        nodeLink.kill("SIGKILL");
      }
    }
  } catch {
    /* already gone */
  }
}

/** Generates nodelink/config.js from the environment unless a custom (marker-less) one exists. */
function writeNodeLinkConfig() {
  const configPath = path.join(NODELINK_DIR, "config.js");
  if (fs.existsSync(configPath) && !fs.readFileSync(configPath, "utf8").includes(MARKER)) {
    console.log("📄 Using existing nodelink/config.js (custom config detected).");
    return;
  }

  const content = [
    `${MARKER} — regenerated on start while this marker is present. Remove the marker to customize.`,
    `import * as defaults from "./dist/config.default.js";`,
    ``,
    `const base = defaults.config ?? defaults.default ?? defaults;`,
    ``,
    `base.server.host = ${JSON.stringify(bindHost)};`,
    `base.server.port = ${port};`,
    `base.server.password = process.env.NODELINK_PASSWORD ?? ${JSON.stringify(
      process.env.NODELINK_PASSWORD || "youshallnotpass"
    )};`,
    ``,
    `base.server.useBunServer = false; // Bun's HTTP server is unavailable under plain Node.js`,
    ``,
    `// YouTube: OAuth via the TV client (refresh token) and NO impostor-song fallback.`,
    `// The mirror fallback picks a fuzzy "best match" from another source when`,
    `// YouTube stream resolution fails — that must never happen silently.`,
    `base.sources.youtube.fallbackSources = [];`,
    `for (const s of ["soundcloud", "deezer", "jiosaavn", "qobuz", "gaana", "vkmusic", "yandexmusic", "audiomack", "bandcamp", "audius", "mixcloud", "bilibili", "bluesky", "nicovideo"]) {`,
    `  if (base.sources[s]) base.sources[s].enabled = false;`,
    `}`,
    ``,
    `const ytRefreshToken = (process.env.NODELINK_SOURCES_YOUTUBE_CLIENTS_SETTINGS_TV_REFRESHTOKEN ?? "").trim();`,
    `const hasYtToken = ytRefreshToken.length > 0 && ytRefreshToken !== '[""]';`,
    `base.sources.youtube.clients.settings.TV.refreshToken = hasYtToken ? [ytRefreshToken] : [""];`,
    `// getOAuthToken=true ONLY while no token exists: it runs the one-time Google`,
    `// device sign-in (prints URL + code, then exits). With a token present it must`,
    `// stay false, or NodeLink re-runs sign-in on every restart.`,
    `base.sources.youtube.getOAuthToken = !hasYtToken;`,
    ``,
    `export const config = base;`,
    `export default base;`,
    ``,
  ].join("\n");

  fs.writeFileSync(configPath, content);
  console.log(`📄 Generated nodelink/config.js (bind ${bindHost}:${port}).`);
}

/**
 * NodeLink loads config.ts before config.js, so a shipped config.ts silently
 * shadows the generated file. The NODELINK_SERVER_* overrides passed to the
 * child process still win, but users deserve to know why their edits to the
 * generated file appear to do nothing.
 */
function warnAboutTsConfigShadow() {
  if (!fs.existsSync(path.join(NODELINK_DIR, "config.ts"))) return;
  console.log(
    "ℹ️  nodelink/config.ts found — NodeLink loads it before the generated config.js. " +
      "The bind host/port/password above are enforced via NODELINK_SERVER_* env overrides, " +
      "so they still apply; edit config.ts (or rename it) for any other setting."
  );
}

function startNodeLink() {
  console.log(`🌿 Starting bundled NodeLink (bind ${bindHost}:${port})…`);
  const child = spawn(process.execPath, ["--dns-result-order=ipv4first", "dist/src/index.js"], {
    cwd: NODELINK_DIR,
    env: {
      ...process.env,
      // NodeLink applies NODELINK_<PATH> overrides AFTER loading its config files,
      // so these beat nodelink/config.ts too (needed on Render, where $PORT must win).
      NODELINK_SERVER_HOST: bindHost,
      NODELINK_SERVER_PORT: String(port),
      NODELINK_SERVER_PASSWORD: process.env.NODELINK_PASSWORD || "youshallnotpass",
    },
    // Detached on POSIX so the whole worker tree shares one process group we can kill.
    detached: process.platform !== "win32",
    windowsHide: true,
    stdio: "inherit",
  });
  child.on("exit", (code, signal) => {
    if (shuttingDown) return;
    console.error(
      `[NodeLink] exited unexpectedly (code ${code}${signal ? ` ${signal}` : ""}) — stopping so it can be restarted.`
    );
    process.exit(1);
  });
  return child;
}

/** Polls NodeLink's REST API until it answers (any response, even 401, proves the server is up). */
async function waitUntilReady(timeoutMs = 90_000) {
  const url = `http://127.0.0.1:${port}/v4/version`;
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, {
        headers: { Authorization: process.env.NODELINK_PASSWORD || "youshallnotpass" },
      });
      // Any HTTP response (200, 401, 404, ...) proves the server is up.
      if (res.status < 500) return true;
    } catch {
      /* not up yet */
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }
  return false;
}

function startBot() {
  try {
    require(path.join(ROOT, "src", "index.js"));
  } catch (error) {
    console.error("❌ Failed to start the bot:", error);
    killNodeLinkTree();
    process.exit(1);
  }
}

(async function main() {
  console.log("🎵 JaMusic V2 launcher");

  if (externalHost) {
    console.log(
      `🔗 NODELINK_HOST is external (${process.env.NODELINK_HOST}) — skipping bundled NodeLink, connecting directly.`
    );
    startBot();
    return;
  }

  require("./install-nodelink.js");
  writeNodeLinkConfig();
  warnAboutTsConfigShadow();
  nodeLink = startNodeLink();

  console.log("⏳ Waiting for NodeLink's API to come up…");
  if (!(await waitUntilReady())) {
    console.error("❌ NodeLink did not become ready in time — check the logs above.");
    process.exit(1);
  }
  console.log(`✅ NodeLink is up on ${bindHost}:${port}.`);

  startBot();
})();

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    if (shuttingDown) return;
    shuttingDown = true;
    console.log(`\n${signal} received — stopping…`);
    killNodeLinkTree();
    process.exit(0);
  });
}

// Never leave the bundled NodeLink (or its workers) behind when this process goes away.
process.on("exit", () => {
  killNodeLinkTree();
});

